# Generated by Django 4.0.3 on 2022-07-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Age', models.IntegerField(default='', max_length=10)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Contact', models.IntegerField(default='', max_length=20)),
                ('Mail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
